Models/Dept.cs
namespace RazorPages.Models;

public enum Dept
{
    None, HR, IT, Payroll
}

Models/Employee.cs
using System.ComponentModel.DataAnnotations;
namespace RazorPages.Models;

public class Employee
{
    public int Id { get; set; }
    [Required]
    [MinLength(2)]
    public string? Name { get; set; }
    [Required]
    [EmailAddress]
    public string? Email { get; set; }
    public string? Photo { get; set; }
    public Dept? Department { get; set; }
}

Pages/Employees/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using RazorPages.Services;
using RazorPages.Models;

namespace RazorPages.Pages.Employees;

public class DeleteModel : PageModel
{
    private readonly IEmployeeRepository employeeRepository;
    [BindProperty]
    public Employee? Employee { get; set; }

    public DeleteModel(IEmployeeRepository employeeRepository)
    {
        this.employeeRepository = employeeRepository;
    }

    public IActionResult OnGet(int id)
    {
        Employee = employeeRepository.GetEmployee(id);
        
        if (Employee == null)
        {
            return RedirectToPage("/NotFound");
        }

        return Page();
    }

    public IActionResult OnPost()
    {
        Employee? deletedEmployee = employeeRepository.Delete(Employee.Id);

        if (deletedEmployee == null)
        {
            return RedirectToPage("/NotFound");
        }

        return RedirectToPage("Index");
    }
}

Pages/Employees/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using RazorPages.Services;
using RazorPages.Models;

namespace RazorPages.Pages.Employees;

public class DetailsModel : PageModel
{
    public Employee Employee { get; set; }
    [TempData]
    public string? Message { get; set; }
    public IEmployeeRepository employeeRepository { get; set; }
    public DetailsModel(IEmployeeRepository employeeRepository)
    {
        this.employeeRepository = employeeRepository;
        Employee = new Employee();
    }

    public IActionResult OnGet(int id = 1)
    {
        Employee = employeeRepository.GetEmployee(id);

        if (Employee == null)
        {
            return RedirectToPage("/NotFound");
        }

        return Page();
    }
}

Pages/Employees/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPages.Services;
using RazorPages.Models;

namespace RazorPages.Pages.Employees;

public class EditModel : PageModel
{
    private readonly IEmployeeRepository employeeRepository;
    private readonly IWebHostEnvironment webHostEnvironment;
    [BindProperty]
    public Employee? Employee { get; set; }
    [BindProperty]
    public IFormFile? Photo { get; set; }
    [BindProperty]
    public bool Notify { get; set; }
    public string? Message { get; set; }

    public EditModel(IEmployeeRepository employeeRepository, IWebHostEnvironment webHostEnvironment)
    {
        this.employeeRepository = employeeRepository;
        this.webHostEnvironment = webHostEnvironment;
    }
    public IActionResult OnGet(int id)
    {
        Employee = employeeRepository.GetEmployee(id);

        if (Employee != null)
        {
            return Page();
        }
        else
        {
            return RedirectToPage("/NotFound");
        }
    }

    public IActionResult OnPost()
    {
        if (ModelState.IsValid)
        {

            if (Photo != null && Employee != null)
            {
                if (Employee.Photo != null)
                {
                    string filepath = Path.Combine(webHostEnvironment.WebRootPath, "images", Employee.Photo);
                    System.IO.File.Delete(filepath);
                }

                Employee.Photo = ProcessUploadFile();
            }

            if (Employee != null)
            {
                Employee = employeeRepository.Update(Employee);
            }

            return RedirectToPage("Index");
        }
        else
        {
            return Page();
        }
    }

    public IActionResult OnPostUpdateNotificationPreferences(int id)
    {
        if (Notify)
        {
            Message = "Thank you for turning on notification";
        }
        else
        {
            Message = "You have turned off email notification";
        }

        TempData["message"] = Message;

        return RedirectToPage("Details", new { id = id });
    }

    public string? ProcessUploadFile()
    {
        string? uniqueFileName = null;

        if (Photo != null)
        {
            string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
            uniqueFileName = Guid.NewGuid().ToString() + "_" + Photo.FileName;
            string filePath = Path.Combine(uploadsFolder, uniqueFileName);

            using (var fileStream = new FileStream(filePath, FileMode.Create))
            {
                Photo.CopyTo(fileStream);
            }
        }

        return uniqueFileName;
    }
}

Pages/Employees/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPages.Models;
using RazorPages.Services;

namespace RazorPages.Pages.Employees;

public class IndexModel : PageModel
{
    private readonly IEmployeeRepository employeeRepository;
    public string Message { get; set; }
    public IEnumerable<Employee>? Employees { get; set; }

    public IndexModel(IEmployeeRepository employeeRepository)
    {
        this.employeeRepository = employeeRepository;
        Message = "Employees";
    }

    public void OnGet()
    {
        Employees = employeeRepository.GetEmployees();
    }
}

Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPages.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}


Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPages.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {

    }
}

Pages/NotFound.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;

namespace RazorPages.Pages;

public class NotFoundModel : PageModel
{
    public void OnGet()
    {

    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPages.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}


Pages/Employees/Delete.cshtml
@page "{id}"
@model RazorPages.Pages.Employees.DeleteModel
@{
    ViewData["Title"] = "Delete";
    ViewData["ShowButtons"] = false;
}

<h1>Delete Confirmation</h1>
<div class="alert alert-danger">
    <partial name="_DisplayEmployeePartial" model=@Model.Employee view-data=@ViewData />
    <h3>Are you sure you want to delete employee - @Model.Employee.Name</h3>
    <form method="post">
        <button type="submit" class="btn btn-danger">Yes</button>
        <a asp-page="/Employees/Index" class="btn btn-primary">No</a>
    </form>
</div>

Pages/Employees/Details.cshtml
@page "/employees/view/{id:range(1,100):int?}"
@using RazorPages.Models
@model RazorPages.Pages.Employees.DetailsModel
@{
    ViewData["Title"] = Model.Employee == null ? "Not Found" : Model.Employee.Name;

    int id = 1;
    string name = "Not Found";
    string email = "notfound@gg.mn";
    string photo = "~/images/no-image.jpg";
    Dept department = Dept.None;

    if (Model.Employee != null)
    {
        id = Model.Employee.Id;
        name = Model.Employee.Name ?? name;
        email = Model.Employee.Email ?? email;
        photo = $"~/images/{Model.Employee.Photo}" ?? photo;
        department = Model.Employee.Department ?? department;
    }
}

<div class="row justify-content-center m-3">
    @if (Model.Message != null)
    {
        <div class="col-sm-8">
            <div class="alert alert-primary">
                @Model.Message
            </div>
        </div>
    }
    <div class="col-sm-8">
        <div class="card">
            <div class="card-header">
                <h1>@name</h1>
            </div>
            <div class="card-body text-center">
                <img class="card-img-top" src="@photo" alt="@name" asp-append-version="true">
                <h4>ID: @id</h4>
                <h4>Email: @email</h4>
                <h4>Department: @department</h4>
            </div>
            <div class="card-footer text-center">
                <a class="btn btn-primary" asp-page="Index">Back</a>
                <a class="btn btn-primary" asp-page="Index">Edit</a>
                <a class="btn btn-danger" asp-page="Index">Delete</a>
            </div>
        </div>
    </div>
</div>

Pages/Employees/Edit.cshtml
@page "{id}/{handler?}"
@model RazorPages.Pages.Employees.EditModel

@{
    string photo = "~/images/no-image.jpg";
    if (Model.Employee != null)
    {
        photo = Model.Employee.Photo != null ? $"~/images/{Model.Employee.Photo}" : photo;
    }
}

<h1>Notification Preferences</h1>
<form method="post" asp-page-handler="UpdateNotificationPreferences">
    <div class="form-check">
        <input asp-for="Notify" class="form-check-input" />
        <label asp-for="Notify" class="form-check-label">
            Receive email notification when you my detail change
        </label>
    </div>
    <button type="submit" class="btn btn-primary">
        Update Notification Preferences
    </button>

</form>

<hr>

<h1>Edit</h1>
<form method="post" class="mt-3" enctype="multipart/form-data" asp-page-handler="OnPost">
    <input hidden type="text" asp-for="Employee.Id">
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">Name:</label>
        <div class="col-sm-10">
            <input class="form-control" type="text" asp-for="Employee.Name" />
        </div>
        <span asp-validation-for="Employee.Name" class="text-danger"></span>
    </div>
    <div class="form-group row">
        <div class="col-sm-2">
            <label class="col-form-label">Email:</label>
        </div>
        <div class="col-sm-10">
            <input class="form-control" type="text" asp-for="Employee.Email" />
        </div>
        <span asp-validation-for="Employee.Email" class="text-danger"></span>
    </div>
    <div class="form-group row">
        <div class="col-sm-2">
            <label class="col-form-label">Department:</label>
        </div>
        <div class="col-sm-10">
            <select class="form-control" asp-for="Employee.Department" asp-items="Html.GetEnumSelectList<Dept>()">
                <option value="">Please Select</option>
            </select>
        </div>
    </div>
    <div class="form-group row col-sm-4 offset-4">
        <img src="@photo" alt="@Model.Employee.Name" asp-append-version="true">
    </div>
    <div class="form-group">
        <div class="col-sm-2 ">
            <label asp-for="Photo" class="col-form-label"></label>
        </div>
        <div class="col-sm-10">
            <div class="custom-file">
                <input asp-for="Photo" class="custom-file-input form-control">
                <label class="custom-file-label">Click here to change photo</label>
            </div>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Edit</button>
            <a class="btn btn-primary" asp-page="/Employees/Index">Back</a>
        </div>
    </div>
    @section Scripts {
    <script>
        $(document).ready(function () {
            $(".custom-file-input").on("change", function () {
                var fileName = $(this).val().split("\\").pop();
                $(this).next(".custom-file-label").html(fileName);
            })
        });
    </script>
    }
</form>

Pages/Employees/Index.cshtml
@page
@using RazorPages.Models;
@model RazorPages.Pages.Employees.IndexModel
@{
    ViewData["Title"] = "Employees";
    ViewData["ShowButtons"] = true;
}

<h1>@Model.Message</h1>

<div class="card-group">
    @foreach (var employee in Model.Employees ?? new List<Employee>())
    {
        <partial name="_DisplayEmployeePartial" model=@employee view-data=@ViewData />
    }
</div>

Pages/Employees/_DisplayEmployeePartial.cshtml
@model Employee
@{
    var showButtons = (bool)ViewData["ShowButtons"];
}

<div class="card" style="width: 20rem;">
    <img class="card-img-top" src="~/images/@Model.Photo" alt="@Model.Name" style="height: 200px;">
    @if (showButtons)
    {
        <div class="card-body">
            <h5 class="card-title">@Model.Name</h5>
            <div class="card-footer text-center">
                <a asp-page="/Employees/Details" asp-route-id="@Model.Id" class="btn btn-primary m-1">View</a>
                <a asp-page="/Employees/Edit" asp-route-id="@Model.Id" class="btn btn-primary m-1">Edit</a>
                <a asp-page="/Employees/Delete" asp-route-id="@Model.Id" class="btn btn-danger m-1">Delete</a>
            </div>
        </div>
    }
</div>

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Hello World</h1>
</div>

Pages/NotFound.cshtml
@page
@model RazorPages.Pages.NotFoundModel

<h1 align="center">404 NOT FOUND</h1>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RazorPages</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RazorPages.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">RazorPages</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Employees/Index">Employees</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - RazorPages - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>